Repository Ureka-High-Five/backend, pull requests merged in 2025-08, with the labels that each got.

#371 Feat[#368] 컨텐츠 등록할때, shorts url도 받도록 수정 + uuid 콜백
  src/main/java/org/highfive/backend/content/dto/request/AdminAddContentRequestDto.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/entity/ContentVector.java
  src/main/java/org/highfive/backend/content/exception/ContentErrorCode.java
  src/main/java/org/highfive/backend/content/repository/jpa/ContentVectorRepository.java
  src/main/java/org/highfive/backend/content/service/AdminContentService.java
  src/main/java/org/highfive/backend/infra/s3/MediaType.java
  src/main/java/org/highfive/backend/infra/s3/dto/ContentsPresignedUrlResponseDto.java
  src/main/java/org/highfive/backend/infra/s3/service/S3Service.java
  src/main/java/org/highfive/backend/shorts/entity/Shorts.java
  src/test/java/org/highfive/backend/common/fixture/ContentFixture.java
  src/test/java/org/highfive/backend/content/service/AdminContentServiceTest.java
Labels: feat

#373 feat[#372]: shortsUrl 필드값 요청 받도록 수정
  src/main/java/org/highfive/backend/content/dto/request/AdminAddContentRequestDto.java
Labels: feat

#375 Feat[#374] 내가 작성한 리뷰 작품 조회시 id값 넘기기
  src/main/java/org/highfive/backend/content/entity/ContentVector.java
  src/main/java/org/highfive/backend/review/repository/jpa/ReviewRepository.java
  src/main/java/org/highfive/backend/user/dto/response/RatedContentResponseDto.java
Labels: feat

#382 Fix[#381]: Tempo 환경에서 OpenTelemetry 로그 Export 비활성화 처리
  src/main/java/org/highfive/backend/infra/docker/docker-compose-dev.yml
Labels: fix

#394 Feat[#393]: 벡터 비교 기반의 컨텐츠만 조회하는 api 개발
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/service/HomeContentService.java
  src/main/resources/application-local.yml
Labels: feat

#404 Fix[#402]: Post Method로의 변경에 따른 AOP 및 API 수정
  src/main/java/org/highfive/backend/action/log/strategy/ClickActionLogStrategy.java
  src/main/java/org/highfive/backend/user/controller/UserLogController.java
  src/main/java/org/highfive/backend/user/service/UserLogService.java
Labels: fix, refactor

#405 Feat[#397]: 금칙어 필터링 API
  src/main/java/org/highfive/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/highfive/backend/global/config/SecurityConfig.java
  src/main/java/org/highfive/backend/slang/SlangController.java
  src/main/java/org/highfive/backend/slang/dto/request/SlangFilterRequestDto.java
  src/main/java/org/highfive/backend/slang/dto/response/SlangFilterResponseDto.java
Labels: feat

#406 Docs : readme 개선
  README.md
Labels: docs

#419 feat[#418]: orderby 연산자 제거
  src/main/java/org/highfive/backend/content/repository/querydsl/ContentQueryRepositoryImpl.java
Labels: fix
