Repository Ureka-High-Five/backend, pull requests merged in 2025-07, with the labels that each got.

#36 [Feature] Oauth(Kakao)와 연동해서 사용자 정보를 가져오는 기능
  .github/workflows/dev-deploy.yml
  build.gradle
  src/main/java/org/highfive/backend/auth/client/KakaoOAuthClient.java
  src/main/java/org/highfive/backend/auth/client/config/KakaoOAuthClientConfig.java
  src/main/java/org/highfive/backend/auth/client/dto/response/KakaoTokenResponseDto.java
  src/main/java/org/highfive/backend/auth/client/dto/response/KakaoUserResponseDto.java
  src/main/java/org/highfive/backend/auth/controller/AuthController.java
  src/main/java/org/highfive/backend/auth/controller/dto/request/OAuthRequestDto.java
  src/main/java/org/highfive/backend/auth/controller/dto/response/TokenResponseDto.java
  src/main/java/org/highfive/backend/auth/service/AuthService.java
  src/main/java/org/highfive/backend/global/code/ErrorCode.java
  src/main/java/org/highfive/backend/user/entity/User.java
  src/main/java/org/highfive/backend/user/repository/UserRepository.java
  src/main/resources/application-dev.yml
  src/test/java/org/highfive/backend/auth/controller/AuthControllerTest.java
  src/test/java/org/highfive/backend/auth/service/AuthServiceTest.java
  src/test/resources/application-test.yml
Labels: feat, chore, test, refactor

#40 FastAPI 클라이언트 모듈 구현
  src/main/java/org/highfive/backend/global/client/fastapi/FastApiClient.java
  src/main/java/org/highfive/backend/global/client/fastapi/dto/RecommendContentsResponseDto.java
  src/main/java/org/highfive/backend/global/code/ErrorCode.java
Labels: feat

#42 ErrorCode 추상화 및 도메인별 관리
  .github/workflows/dev-deploy.yml
  src/main/java/org/highfive/backend/auth/client/KakaoOAuthClient.java
  src/main/java/org/highfive/backend/auth/client/exception/AuthErrorCode.java
  src/main/java/org/highfive/backend/global/client/fastapi/FastApiClient.java
  src/main/java/org/highfive/backend/global/client/fastapi/exception/FastApiErrorCode.java
  src/main/java/org/highfive/backend/global/code/ErrorCode.java
  src/main/java/org/highfive/backend/global/code/GlobalErrorCode.java
  src/main/java/org/highfive/backend/global/exception/ErrorResponseDto.java
  src/main/java/org/highfive/backend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/org/highfive/backend/global/exception/handler/ValidationExceptionHandler.java
  src/test/java/org/highfive/backend/auth/controller/AuthControllerTest.java
Labels: refactor

#47 Feat[#39] 리뷰 생성 및 수정 기능 추가
  src/main/java/org/highfive/backend/content/controller/ReviewController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ReviewMapper.java
  src/main/java/org/highfive/backend/content/dto/request/CreateReviewRequestDto.java
  src/main/java/org/highfive/backend/content/dto/request/UpdateReviewRequestDto.java
  src/main/java/org/highfive/backend/content/entity/review/Review.java
  src/main/java/org/highfive/backend/content/exception/ContentErrorCode.java
  src/main/java/org/highfive/backend/content/exception/ReviewErrorCode.java
  src/main/java/org/highfive/backend/content/repository/ContentRepository.java
  src/main/java/org/highfive/backend/content/repository/ReviewRepository.java
  src/main/java/org/highfive/backend/content/service/ReviewService.java
  src/main/java/org/highfive/backend/global/code/SuccessCode.java
Labels: fix, feat

#48 Feat/onboarding init contents
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/dto/OnboardingInitContentsResponseDto.java
  src/main/java/org/highfive/backend/content/dto/TopContentByGenreDto.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/mapper/ReviewMapper.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/repository/ContentRepository.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/global/config/QueryDslConfig.java
Labels: feat

#51 [Feature] 토큰 기반 인증 로직 구현
  .github/workflows/dev-deploy.yml
  build.gradle
  src/main/java/org/highfive/backend/auth/client/KakaoOAuthClient.java
  src/main/java/org/highfive/backend/auth/config/KakaoOAuthClientConfig.java
  src/main/java/org/highfive/backend/auth/exception/AuthErrorCode.java
  src/main/java/org/highfive/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/highfive/backend/auth/jwt/JwtUtils.java
  src/main/java/org/highfive/backend/auth/service/AuthService.java
  src/main/java/org/highfive/backend/global/config/SecurityConfing.java
  src/main/java/org/highfive/backend/infra/docker/docker-compose-dev.yml
  src/main/java/org/highfive/backend/user/entity/User.java
  src/main/java/org/highfive/backend/user/exception/UserErrorCode.java
  src/main/java/org/highfive/backend/user/repository/UserRepository.java
  src/main/resources/application-dev.yml
  src/test/java/org/highfive/backend/auth/controller/AuthControllerTest.java
  src/test/resources/application-test.yml
Labels: feat, chore, docs

#54 Feat[#49] 리뷰 조회 및 삭제 API 추가
  src/main/java/org/highfive/backend/content/controller/ReviewController.java
  src/main/java/org/highfive/backend/content/dto/response/ReviewSimpleResponseDto.java
  src/main/java/org/highfive/backend/content/entity/review/Review.java
  src/main/java/org/highfive/backend/content/exception/ContentErrorCode.java
  src/main/java/org/highfive/backend/content/exception/ReviewErrorCode.java
  src/main/java/org/highfive/backend/content/repository/ReviewQueryRepository.java
  src/main/java/org/highfive/backend/content/repository/ReviewQueryRepositoryImpl.java
  src/main/java/org/highfive/backend/content/repository/ReviewRepository.java
  src/main/java/org/highfive/backend/content/service/ReviewService.java
  src/main/java/org/highfive/backend/global/code/SuccessCode.java
  src/main/java/org/highfive/backend/global/dto/CursorPageResponse.java
  src/main/java/org/highfive/backend/user/entity/User.java
Labels: fix, feat

#59 [Feature] 로그아웃 구현
  src/main/java/org/highfive/backend/auth/controller/AuthController.java
  src/main/java/org/highfive/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/highfive/backend/auth/repository/redis/TokenRedisRepository.java
  src/main/java/org/highfive/backend/auth/service/AuthService.java
  src/main/java/org/highfive/backend/auth/service/TokenService.java
  src/main/java/org/highfive/backend/global/config/SecurityConfing.java
Labels: feat

#68 refactor[#67]: 파일 구조를 변경했습니다.
  src/main/java/org/highfive/backend/auth/service/AuthService.java
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/response/OnboardingInitContentsResponseDto.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/user/dto/mapper/UserMapper.java
Labels: refactor

#70 [Feature] 사용자가 작성한 리뷰를 조회하는 API 구현
  .github/workflows/dev-deploy.yml
  src/main/java/org/highfive/backend/auth/controller/AuthController.java
  src/main/java/org/highfive/backend/auth/dto/request/OAuthRequestDto.java
  src/main/java/org/highfive/backend/auth/dto/request/ReissueRequestDto.java
  src/main/java/org/highfive/backend/auth/exception/AuthErrorCode.java
  src/main/java/org/highfive/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/highfive/backend/auth/service/AuthService.java
  src/main/java/org/highfive/backend/auth/service/TokenService.java
  src/main/java/org/highfive/backend/auth/service/TokenType.java
  src/main/java/org/highfive/backend/content/controller/ReviewController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/response/ContentDetailResponseDto.java
  src/main/java/org/highfive/backend/content/dto/response/ContentMyReviewResponseDto.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/repository/ReviewRepository.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/content/service/ReviewService.java
  src/main/java/org/highfive/backend/global/config/SecurityConfing.java
  src/main/java/org/highfive/backend/infra/docker/docker-compose-dev.yml
  src/main/java/org/highfive/backend/user/controller/UserController.java
  src/main/resources/application-dev.yml
Labels: feat

#72 Feat[#64]: 온보딩 작품 클릭 시 유사한 작품 조회
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/controller/OnboardingController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/request/OnboardingSelectContentRequestDto.java
  src/main/java/org/highfive/backend/content/dto/response/GenreCountDto.java
  src/main/java/org/highfive/backend/content/dto/response/OnboardingContentDto.java
  src/main/java/org/highfive/backend/content/dto/response/OnboardingSelectContentResponseDto.java
  src/main/java/org/highfive/backend/content/repository/ContentQueryRepository.java
  src/main/java/org/highfive/backend/content/repository/ContentRepository.java
  src/main/java/org/highfive/backend/content/repository/QueryDslContentRepository.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/main/java/org/highfive/backend/global/RecommendType.java
  src/main/java/org/highfive/backend/global/client/fastapi/FastApiClient.java
  src/main/java/org/highfive/backend/user/service/UserService.java
Labels: feat

#76 Feat[#75]: 컨텐츠 검색
  src/main/java/org/highfive/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/response/SearchContentResponseDto.java
  src/main/java/org/highfive/backend/content/entity/repository/MetaInfoContentsRepository.java
  src/main/java/org/highfive/backend/content/repository/ContentRepository.java
  src/main/java/org/highfive/backend/content/repository/ReviewQueryRepository.java
  src/main/java/org/highfive/backend/content/repository/ReviewQueryRepositoryImpl.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/global/config/SecurityConfing.java
  src/main/java/org/highfive/backend/global/config/WebConfig.java
  src/main/java/org/highfive/backend/global/exception/handler/GlobalExceptionHandler.java
Labels: feat

#86 Fix[#85]: 버그 대응
  src/main/java/org/highfive/backend/content/repository/ContentRepository.java
Labels: fix

#93 Test [#74] 컨텐츠 상세 조회 테스트 코드 작성
  src/test/java/org/highfive/backend/common/fixture/ContentFixture.java
  src/test/java/org/highfive/backend/common/fixture/MetaInfoContentsFixture.java
  src/test/java/org/highfive/backend/common/fixture/MetaInfoFixture.java
  src/test/java/org/highfive/backend/content/integration/ContentIntegrationTest.java
  src/test/java/org/highfive/backend/content/repository/ContentRepositoryTest.java
  src/test/java/org/highfive/backend/content/service/ContentServiceTest.java
Labels: test

#94 chore[#92]: JaCoco + Codecov 연동 (테스트 커버리지 80%)
  .codecov.yml
  .github/workflows/test-coverage.yml
  build.gradle
  src/main/java/org/highfive/backend/auth/service/AuthService.java
Labels: chore

#98 test[#97]: 토큰 검증 로직 주석 해제
  src/main/java/org/highfive/backend/auth/jwt/JwtAuthenticationFilter.java
  src/test/java/org/highfive/backend/content/integration/ContentIntegrationTest.java
Labels: chore

#96 Fix[#91]: 초기 온보딩 dto 수정
  src/main/java/org/highfive/backend/content/dto/response/MostPopularContentPerGenreDto.java
  src/main/java/org/highfive/backend/content/dto/response/OnboardingInitContentsResponseDto.java
  src/main/java/org/highfive/backend/content/repository/ContentRepository.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
Labels: fix

#106 Test[#103]: Oauth 테스트 코드 작성
  .github/workflows/dev-deploy.yml
  build.gradle
  src/main/java/org/highfive/backend/auth/controller/AuthController.java
  src/main/java/org/highfive/backend/auth/service/AuthService.java
  src/main/java/org/highfive/backend/user/code/UserErrorCode.java
  src/test/java/org/highfive/backend/BackendApplicationTests.java
  src/test/java/org/highfive/backend/auth/controller/AuthControllerTest.java
  src/test/java/org/highfive/backend/auth/repository/redis/TokenRedisRepositoryTest.java
  src/test/java/org/highfive/backend/auth/service/AuthServiceTest.java
  src/test/java/org/highfive/backend/config/EmbeddedRedisConfig.java
  src/test/resources/application-test.yml
Labels: test

#107 Test[#105]: 온보딩 작품 선택 테스트
  src/main/java/org/highfive/backend/content/controller/OnboardingController.java
  src/main/java/org/highfive/backend/content/repository/QueryDslContentRepository.java
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/test/java/org/highfive/backend/content/controller/OnboardingControllerTest.java
  src/test/java/org/highfive/backend/content/integration/OnboardingIntegrationTest.java
  src/test/java/org/highfive/backend/content/repository/QueryDslContentRepositoryTest.java
  src/test/java/org/highfive/backend/content/service/OnboardingServiceTest.java
Labels: test

#111 Hotfix[#110]: CORS 버그 문제 #110
  src/main/java/org/highfive/backend/global/config/WebConfig.java
Labels: fix

#112 Test[#108]: 온보딩 제출 테스트
  src/test/java/org/highfive/backend/user/controller/UserControllerTest.java
  src/test/java/org/highfive/backend/user/service/UserServiceTest.java
Labels: test

#114 Test[#95] Review 기능 관련 테스트 코드 작성
  src/main/java/org/highfive/backend/content/dto/request/UpdateReviewRequestDto.java
  src/main/java/org/highfive/backend/content/exception/ReviewErrorCode.java
  src/main/java/org/highfive/backend/content/service/ReviewService.java
  src/test/java/org/highfive/backend/common/fixture/ReviewFixture.java
  src/test/java/org/highfive/backend/common/fixture/UserFixture.java
  src/test/java/org/highfive/backend/content/integration/ReviewIntegrationTest.java
  src/test/java/org/highfive/backend/content/repository/ReviewQueryRepositoryTest.java
  src/test/java/org/highfive/backend/content/service/ReviewServiceTest.java
Labels: test

#117 Refactor[#116] 컨텐츠 상세 정보 조회, 리뷰 CRUD 관련 기능 리팩토링
  src/main/java/org/highfive/backend/content/controller/ReviewController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/response/ContentDetailResponseDto.java
  src/main/java/org/highfive/backend/content/repository/ContentQueryRepository.java
  src/main/java/org/highfive/backend/content/repository/QueryDslContentRepository.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/content/service/ReviewService.java
  src/test/java/org/highfive/backend/common/fixture/ContentFixture.java
  src/test/java/org/highfive/backend/content/integration/ContentIntegrationTest.java
  src/test/java/org/highfive/backend/content/service/ContentServiceTest.java
Labels: fix, test, refactor

#121 Hotfix[#120]: CORS - 인증이 필요없는 url 추가
  src/main/java/org/highfive/backend/content/repository/MetaInfoContentsRepository.java
  src/main/java/org/highfive/backend/content/repository/MetaInfoRepository.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/curation/controller/CurationController.java
  src/main/java/org/highfive/backend/curation/dto/request/CreateCurationRequestDto.java
  src/main/java/org/highfive/backend/curation/dto/request/NoDuplicate.java
  src/main/java/org/highfive/backend/curation/dto/request/NoDuplicateValidator.java
  src/main/java/org/highfive/backend/curation/entity/Curation.java
  src/main/java/org/highfive/backend/curation/entity/CurationContents.java
  src/main/java/org/highfive/backend/curation/repository/CurationRepository.java
  src/main/java/org/highfive/backend/curation/service/CurationService.java
  src/main/java/org/highfive/backend/user/service/UserService.java
  src/test/java/org/highfive/backend/content/integration/ContentIntegrationTest.java
  src/test/java/org/highfive/backend/content/integration/OnboardingIntegrationTest.java
  src/test/java/org/highfive/backend/content/repository/ContentRepositoryTest.java
  src/test/java/org/highfive/backend/content/service/ContentServiceTest.java
  src/test/java/org/highfive/backend/user/service/UserServiceTest.java
Labels: fix

#125 Hotfix[#124]: posterUrl -> thumbnailUrl로 변경
  src/main/java/org/highfive/backend/content/dto/response/OnboardingSelectContentResponseDto.java
  src/test/java/org/highfive/backend/content/controller/OnboardingControllerTest.java
Labels: fix

#128 Feature[#127]: 큐레이션 단건 조회 API 구현
  src/main/java/org/highfive/backend/content/exception/ContentErrorCode.java
  src/main/java/org/highfive/backend/curation/controller/CurationController.java
  src/main/java/org/highfive/backend/curation/dto/mapper/CurationMapper.java
  src/main/java/org/highfive/backend/curation/dto/response/CurationDetailResponseDto.java
  src/main/java/org/highfive/backend/curation/entity/CurationContents.java
  src/main/java/org/highfive/backend/curation/exception/CurationErrorCode.java
  src/main/java/org/highfive/backend/curation/repository/jpa/CurationRepository.java
  src/main/java/org/highfive/backend/curation/repository/querydsl/CurationQueryRepository.java
  src/main/java/org/highfive/backend/curation/service/CurationService.java
  src/main/java/org/highfive/backend/global/dto/Response.java
Labels: feat

#119 Refactor[#118]: 초기 온보딩, 온보딩 선택, 온보딩 제출, 홈 컨텐츠 조회 리팩토링
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/controller/HomeContentController.java
  src/main/java/org/highfive/backend/content/controller/OnboardingController.java
  src/main/java/org/highfive/backend/content/dto/response/HomeContentsResponseDto.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/content/service/HomeContentService.java
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/main/java/org/highfive/backend/user/controller/UserController.java
  src/main/java/org/highfive/backend/user/service/UserService.java
  src/main/resources/application-local.yml
  src/test/java/org/highfive/backend/content/controller/ContentControllerTest.java
  src/test/java/org/highfive/backend/content/controller/OnboardingControllerTest.java
  src/test/java/org/highfive/backend/content/service/ContentServiceTest.java
  src/test/java/org/highfive/backend/content/service/OnboardingServiceTest.java
  src/test/java/org/highfive/backend/content/service/ReviewServiceTest.java
  src/test/java/org/highfive/backend/user/controller/UserControllerTest.java
  src/test/java/org/highfive/backend/user/service/UserServiceTest.java
Labels: test, refactor

#131 Feat[#123]: 백오피스 컨텐츠 추가 구현
  src/main/java/org/highfive/backend/content/controller/AdminContentController.java
  src/main/java/org/highfive/backend/content/controller/HomeContentController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/request/AdminAddContentRequestDto.java
  src/main/java/org/highfive/backend/content/dto/response/AdminAddContentResponseDto.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/exception/MetaInfoErrorCode.java
  src/main/java/org/highfive/backend/content/repository/MetaInfoRepository.java
  src/main/java/org/highfive/backend/content/repository/jpa/MetaInfoRepository.java
  src/main/java/org/highfive/backend/content/service/AdminContentService.java
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/main/java/org/highfive/backend/global/client/fastapi/FastApiClient.java
  src/main/java/org/highfive/backend/global/client/fastapi/dto/response/FastApiVectorFromGenresDto.java
  src/main/java/org/highfive/backend/global/code/GlobalErrorCode.java
  src/main/java/org/highfive/backend/user/entity/User.java
  src/test/java/org/highfive/backend/common/fixture/UserFixture.java
  src/test/java/org/highfive/backend/content/integration/ContentIntegrationTest.java
  src/test/java/org/highfive/backend/content/integration/OnboardingIntegrationTest.java
  src/test/java/org/highfive/backend/content/repository/ContentRepositoryTest.java
  src/test/java/org/highfive/backend/content/service/AdminContentServiceTest.java
  src/test/java/org/highfive/backend/content/service/OnboardingServiceTest.java
Labels: feat

#135 Feat[#129] : 컨텐츠 영상 조회 기능 구현
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/dto/response/ContentVideoResponseDto.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/service/ContentService.java
Labels: feat

#137 Feature[#134]: 나의 큐레이션 조회 API 구현
  src/main/java/org/highfive/backend/content/service/ContentService.java
  src/main/java/org/highfive/backend/curation/controller/CurationController.java
  src/main/java/org/highfive/backend/curation/dto/mapper/CurationMapper.java
  src/main/java/org/highfive/backend/curation/dto/response/MyCurationResponseDto.java
  src/main/java/org/highfive/backend/curation/repository/jpa/CurationRepository.java
  src/main/java/org/highfive/backend/curation/repository/querydsl/CurationQueryRepository.java
  src/main/java/org/highfive/backend/curation/service/CurationService.java
Labels: feat

#147 Fix[#145]: dto에 id 필드 추가
  src/main/java/org/highfive/backend/content/dto/response/HomeContentsResponseDto.java
  src/main/java/org/highfive/backend/content/service/HomeContentService.java
Labels: fix

#139 Feat[#133]: 백오피스 컨텐츠 수정 기능
  src/main/java/org/highfive/backend/content/controller/AdminContentController.java
  src/main/java/org/highfive/backend/content/dto/request/AdminUpdateContentRequestDto.java
  src/main/java/org/highfive/backend/content/dto/response/AdminAddContentResponseDto.java
  src/main/java/org/highfive/backend/content/dto/response/AdminUpdateContentResponseDto.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/repository/MetaInfoContentsRepository.java
  src/main/java/org/highfive/backend/content/repository/QueryDslContentRepository.java
  src/main/java/org/highfive/backend/content/repository/jpa/MetaInfoRepository.java
  src/main/java/org/highfive/backend/content/service/AdminContentService.java
  src/test/java/org/highfive/backend/common/fixture/AdminDtoFixture.java
  src/test/java/org/highfive/backend/content/integration/ContentIntegrationTest.java
  src/test/java/org/highfive/backend/content/service/AdminContentServiceTest.java
Labels: feat

#153 Feature[#151]: Curation 삭제 API 구현
  src/main/java/org/highfive/backend/content/exception/ReviewErrorCode.java
  src/main/java/org/highfive/backend/curation/controller/CurationController.java
  src/main/java/org/highfive/backend/curation/exception/CurationErrorCode.java
  src/main/java/org/highfive/backend/curation/service/CurationService.java
Labels: feat

#166 Refactor[#161] : 컨텐츠 상세 조회, 리뷰 조회 리팩토링
  src/main/java/org/highfive/backend/content/controller/ReviewController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/dto/response/ContentDetailResponseDto.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/repository/ReviewQueryRepository.java
  src/main/java/org/highfive/backend/content/repository/ReviewQueryRepositoryImpl.java
  src/main/java/org/highfive/backend/content/service/ReviewService.java
  src/test/java/org/highfive/backend/content/integration/ReviewIntegrationTest.java
  src/test/java/org/highfive/backend/content/repository/ReviewQueryRepositoryTest.java
  src/test/java/org/highfive/backend/content/service/ReviewServiceTest.java
Labels: refactor

#168 Feat[#152] : 쇼츠 댓글 생성 기능 구현
  src/main/java/org/highfive/backend/content/controller/ShortsController.java
  src/main/java/org/highfive/backend/content/dto/mapper/ShortsCommentMapper.java
  src/main/java/org/highfive/backend/content/dto/request/CreateShortsCommentRequestDto.java
  src/main/java/org/highfive/backend/content/entity/shorts/ShortsComment.java
  src/main/java/org/highfive/backend/content/exception/ShortsErrorCode.java
  src/main/java/org/highfive/backend/content/repository/jpa/ShortsCommentRepository.java
  src/main/java/org/highfive/backend/content/service/ShortsService.java
  src/main/java/org/highfive/backend/global/config/SecurityConfig.java
Labels: feat, chore

#173 refactor[#172]: CreateAt, UpdatedAt 모든 엔티티에 붙이기
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/entity/metadata/Episode.java
  src/main/java/org/highfive/backend/content/entity/metadata/MetaInfo.java
  src/main/java/org/highfive/backend/content/entity/metadata/MetaInfoContents.java
  src/main/java/org/highfive/backend/content/entity/metadata/Series.java
  src/main/java/org/highfive/backend/content/entity/review/Review.java
  src/main/java/org/highfive/backend/content/entity/shorts/Shorts.java
  src/main/java/org/highfive/backend/content/entity/shorts/ShortsComment.java
  src/main/java/org/highfive/backend/content/entity/shorts/log/ShortsLikeTimeLog.java
  src/main/java/org/highfive/backend/curation/entity/Curation.java
  src/main/java/org/highfive/backend/curation/entity/CurationContents.java
  src/main/java/org/highfive/backend/global/entity/BaseEntity.java
  src/main/java/org/highfive/backend/user/entity/User.java
  src/main/java/org/highfive/backend/user/entity/log/UserLog.java
  src/main/java/org/highfive/backend/user/entity/log/WatchInfo.java
  src/main/java/org/highfive/backend/user/entity/preference/PreferMetaInfo.java
Labels: refactor

#176 Chore[#175]: 필드이름 변경 및 Max를 2025로 변경
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/main/java/org/highfive/backend/user/dto/request/SubmitOnboardingRequestDto.java
Labels: refactor

#180 Feature[#171] 쇼츠 좋아요 취소 구현
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/request/ShortsDislikeRequestDto.java
  src/main/java/org/highfive/backend/shorts/entity/ShortsLikeTimeLog.java
  src/main/java/org/highfive/backend/shorts/exception/ShortsErrorCode.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsLikeTimeLogRepository.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsRepository.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
  src/test/java/org/highfive/backend/content/integration/ShortsIntegrationTest.java
Labels: feat

#182 Feat[#178]: 쇼츠에서 자신이 누른 좋아요 표시 기능
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/RecommendShortsResponseDto.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsAndLikedItemDto.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
  src/test/java/org/highfive/backend/common/fixture/UserFixture.java
  src/test/java/org/highfive/backend/content/controller/ShortsControllerTest.java
  src/test/java/org/highfive/backend/content/service/ShortsServiceTest.java
Labels: feat

#184 Feat[#177] : 쇼츠 댓글 단건 조회 기능
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsCommentMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/GetShortsCommentResponseDto.java
  src/main/java/org/highfive/backend/shorts/entity/ShortsComment.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsCommentRepository.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: feat

#190 Feature[#189]: 내 정보 조회 구현
  src/main/java/org/highfive/backend/user/controller/UserController.java
  src/main/java/org/highfive/backend/user/dto/mapper/UserMapper.java
  src/main/java/org/highfive/backend/user/dto/response/UserInfoResponseDto.java
  src/main/java/org/highfive/backend/user/service/UserService.java
Labels: feat

#191 Feat[#183]: 쇼츠 댓글 시간대별 일부 댓글 조회
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsCommentMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsCommentsByTimeResponseDto.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsCommentRepository.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
  src/test/java/org/highfive/backend/common/fixture/UserFixture.java
  src/test/java/org/highfive/backend/config/TestJpaAuditingConfig.java
  src/test/java/org/highfive/backend/shorts/repository/jpa/ShortsCommentRepositoryTest.java
Labels: feat

#195 Feature[#192] 사용자가 좋아요 누른 쇼츠 목록 조회
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsLikedUserItemDto.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsLikeTimeLogRepository.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: feat

#208 Feat[#140]: 백오피스 컨텐츠 삭제 기능
  src/main/java/org/highfive/backend/auth/aop/AdminOnly.java
  src/main/java/org/highfive/backend/auth/aop/AdminOnlyAspect.java
  src/main/java/org/highfive/backend/content/controller/AdminContentController.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/content/exception/ContentErrorCode.java
  src/main/java/org/highfive/backend/content/service/AdminContentService.java
  src/test/java/org/highfive/backend/content/service/AdminContentServiceTest.java
Labels: feat

#206 Feature[#144] : 컨텐츠 시청 시간 로그 생성 기능 구현
  src/main/java/org/highfive/backend/content/exception/ContentErrorCode.java
  src/main/java/org/highfive/backend/shorts/entity/Shorts.java
  src/main/java/org/highfive/backend/user/controller/UserLogController.java
  src/main/java/org/highfive/backend/user/dto/mapper/UserLogMapper.java
  src/main/java/org/highfive/backend/user/dto/request/CreateContentWatchLogRequestDto.java
  src/main/java/org/highfive/backend/user/entity/log/ActionType.java
  src/main/java/org/highfive/backend/user/entity/log/UserLog.java
  src/main/java/org/highfive/backend/user/exception/UserLogErrorCode.java
  src/main/java/org/highfive/backend/user/repository/UserLogRepository.java
  src/main/java/org/highfive/backend/user/service/UserLogService.java
Labels: feat, refactor

#210 Feat[#209]: 쇼츠 아이디로 쇼츠 조회
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsResponseDto.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: feat

#214 Feat[#207] : 컨텐츠 id 기반 쇼츠 단건 조회
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsMapper.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsRepository.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: feat

#215 Chore[#212] 배포용 RDS와 Entity간 필드 동기화
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/global/entity/BaseEntity.java
  src/main/java/org/highfive/backend/metadata/entity/Episode.java
  src/main/java/org/highfive/backend/shorts/entity/ShortsComment.java
Labels: chore, refactor

#217 Chore[#216] Users 테이블 embedding text로 변경
  src/main/java/org/highfive/backend/metadata/entity/Episode.java
  src/main/java/org/highfive/backend/user/entity/User.java
Labels: feat, chore

#218 Feat[#213]: 백오피스 모든 사용자 조회 무한스크롤 api
  src/main/java/org/highfive/backend/content/service/AdminContentService.java
  src/main/java/org/highfive/backend/shorts/repository/querydsl/ShortsCommentQueryRepository.java
  src/main/java/org/highfive/backend/user/controller/AdminUserController.java
  src/main/java/org/highfive/backend/user/dto/mapper/UserMapper.java
  src/main/java/org/highfive/backend/user/dto/response/GetAllUserResponseDto.java
  src/main/java/org/highfive/backend/user/repository/querydsl/UserQueryRepository.java
  src/main/java/org/highfive/backend/user/service/AdminUserService.java
Labels: feat

#226 Chore[#223] Project에 AWS MongoDB 연동하기
  .github/workflows/dev-deploy.yml
  build.gradle
  src/main/java/org/highfive/backend/infra/docker/docker-compose-dev.yml
  src/main/java/org/highfive/backend/infra/docker/docker-compose-local.yml
  src/main/resources/application-dev.yml
Labels: chore

#228 Refactor[#227]: 추천 쇼츠 무한 스크롤 시 응답 dto 변경
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/RecommendShortsResponseDto.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsResponseDto.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
  src/test/java/org/highfive/backend/content/controller/ShortsControllerTest.java
  src/test/java/org/highfive/backend/content/service/ShortsServiceTest.java
Labels: test, refactor

#224 Feat[#221]: 백오피스 사용자 검색 API
  src/main/java/org/highfive/backend/user/controller/AdminUserController.java
  src/main/java/org/highfive/backend/user/dto/mapper/UserMapper.java
  src/main/java/org/highfive/backend/user/dto/response/SearchUserResponseDto.java
  src/main/java/org/highfive/backend/user/repository/jpa/UserRepository.java
  src/main/java/org/highfive/backend/user/repository/querydsl/UserQueryRepository.java
  src/main/java/org/highfive/backend/user/service/AdminUserService.java
Labels: feat

#238 Fix[#237]: 쇼츠 댓글 시간별 일부 조회 시 무한루프 발생 해결
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: fix

#239 Fix[#232] : 유저가 한 컨텐츠에 하나의 리뷰만 달 수 있도록 수정
  src/main/java/org/highfive/backend/review/exception/ReviewErrorCode.java
  src/main/java/org/highfive/backend/review/repository/jpa/ReviewRepository.java
  src/main/java/org/highfive/backend/review/service/ReviewService.java
Labels: fix

#236 Feat[#234]: 행동 로그를 MongoDB에 저장
  src/main/java/org/highfive/backend/action/Action.java
  src/main/java/org/highfive/backend/action/ActionLogAspect.java
  src/main/java/org/highfive/backend/action/ActionLogRepository.java
  src/main/java/org/highfive/backend/action/ActionLogService.java
  src/main/java/org/highfive/backend/action/ActionLogStamp.java
  src/main/java/org/highfive/backend/action/log/ActionLog.java
  src/main/java/org/highfive/backend/action/log/ActionLogStrategyFactory.java
  src/main/java/org/highfive/backend/action/log/strategy/ActionLogStrategy.java
  src/main/java/org/highfive/backend/action/log/strategy/ClickActionLogStrategy.java
  src/main/java/org/highfive/backend/action/log/strategy/LikeActionLogStrategy.java
  src/main/java/org/highfive/backend/action/log/strategy/RatingActionLogStrategy.java
  src/main/java/org/highfive/backend/action/log/strategy/WatchActionLogStrategy.java
  src/main/java/org/highfive/backend/auth/exception/AuthErrorCode.java
  src/main/java/org/highfive/backend/content/controller/ContentController.java
  src/main/java/org/highfive/backend/content/exception/ContentErrorCode.java
  src/main/java/org/highfive/backend/review/controller/ReviewController.java
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/user/code/UserErrorCode.java
  src/main/java/org/highfive/backend/user/controller/UserLogController.java
Labels: feat

#242 Feat[#240] Spring 서버 RabbitMQ 메시지 재요청 처리 #240
  src/main/java/org/highfive/backend/BackendApplication.java
  src/main/java/org/highfive/backend/global/client/messaging/RecommendationMessageProducer.java
  src/main/java/org/highfive/backend/global/config/MessageRetryConfig.java
  src/main/java/org/highfive/backend/rabbitmq/TestRunner.java
  src/main/java/org/highfive/backend/rabbitmq/config/RabbitMQConfig.java
  src/main/java/org/highfive/backend/rabbitmq/exception/MessageDeliveryException.java
  src/main/java/org/highfive/backend/rabbitmq/exception/MessageException.java
  src/main/java/org/highfive/backend/rabbitmq/producer/RecommendationMessageProducer.java
  src/test/java/org/highfive/backend/rabbitmq/producer/RecommendationMessageProducerIntegrationTest.java
Labels: feat

#247 Feat[#241] Redis에 저장된 유저 벡터 가져오는 기능 추가
  src/main/java/org/highfive/backend/auth/repository/redis/TokenRedisRepository.java
  src/main/java/org/highfive/backend/content/service/HomeContentService.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
  src/main/java/org/highfive/backend/user/repository/redis/UserRedisRepository.java
  src/test/java/org/highfive/backend/content/service/ShortsServiceTest.java
Labels: feat

#255 Feat[#252] 유저 벡터값, 컨텐츠 벡터값 테이블 분리
  src/main/java/org/highfive/backend/content/repository/jpa/ContentRepository.java
  src/main/java/org/highfive/backend/content/service/HomeContentService.java
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/main/java/org/highfive/backend/global/client/fastapi/FastApiClient.java
  src/main/java/org/highfive/backend/global/client/fastapi/dto/response/FastApiRecommendResponseDto.java
  src/main/java/org/highfive/backend/user/entity/User.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/java/org/highfive/backend/content/service/OnboardingServiceTest.java
Labels: feat

#258 refactor[#257]: redis에서 가져온 유저 벡터 데이터 맨앞, 맨뒤 따옴표 제거하기
  src/main/java/org/highfive/backend/content/service/HomeContentService.java
  src/main/java/org/highfive/backend/global/util/VectorUtil.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: feat

#263 Feat[#259] 사용자별 추천 쇼츠 영상 제공
  src/main/java/org/highfive/backend/shorts/config/RedisConfig.java
  src/main/java/org/highfive/backend/shorts/dto/ShortsDto.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsMapper.java
  src/main/java/org/highfive/backend/shorts/entity/Shorts.java
  src/main/java/org/highfive/backend/shorts/entity/ShortsComment.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsLikeTimeLogRepository.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsRedisRepository.java
  src/main/java/org/highfive/backend/shorts/repository/jpa/ShortsRepository.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
  src/test/java/org/highfive/backend/content/service/ShortsServiceTest.java
Labels: feat

#266 Fix[#262] : 서버의 log가 저장되도록 수정
  src/main/resources/logback-spring.xml
Labels: fix

#268 docs[#267]: 오타 제거
  src/main/resources/logback-spring.xml
Labels: feat

#272 Feat[#265]: 금칙어 필터 추가
  build.gradle
  src/main/java/org/highfive/backend/global/exception/BusinessException.java
  src/main/java/org/highfive/backend/review/service/ReviewService.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
  src/main/java/org/highfive/backend/slang/Slang.java
  src/main/java/org/highfive/backend/slang/SlangErrorCode.java
  src/main/java/org/highfive/backend/slang/SlangRepository.java
  src/main/java/org/highfive/backend/slang/SlangValidator.java
  src/main/java/org/highfive/backend/slang/config/TrieConfig.java
  src/main/java/org/highfive/backend/slang/service/AhoCorasickSlangFilterService.java
  src/main/java/org/highfive/backend/slang/service/SlangHolder.java
Labels: feat

#280 Fix[#277] : Log file 경로 수정 및 슬랙 메세지 스타일 변경
  src/main/java/org/highfive/backend/infra/docker/alert-watcher.sh
Labels: fix

#278 Feat[#274]: 온보딩 제출 시 레디스에 사용자 벡터 저장
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/main/java/org/highfive/backend/global/client/fastapi/FastApiClient.java
  src/main/java/org/highfive/backend/global/client/fastapi/dto/request/FastApiOnboardingRequestDto.java
  src/main/java/org/highfive/backend/user/repository/redis/UserRedisRepository.java
  src/test/java/org/highfive/backend/content/service/OnboardingServiceTest.java
Labels: feat

#285 Feat[#281] : 홈 화면에 큐레이션 조회 추가
  src/main/java/org/highfive/backend/content/dto/response/HomeContentsResponseDto.java
  src/main/java/org/highfive/backend/content/service/HomeContentService.java
  src/main/java/org/highfive/backend/curation/dto/mapper/CurationMapper.java
  src/main/java/org/highfive/backend/curation/repository/jpa/CurationRepository.java
Labels: feat

#287 Refactor[#286] : 쇼츠 댓글 단건 조회 Response에 commnetId 추가
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsCommentMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/GetShortsCommentResponseDto.java
Labels: refactor

#288 Feat[#284]: 쇼츠 댓글 id 기준으로 무한 스크롤 조회
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsCommentMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsCommentsResponseDto.java
  src/main/java/org/highfive/backend/shorts/repository/querydsl/ShortsCommentQueryRepository.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: feat

#295 Feat[#294] OutBoxPattern을 적용하기 위해 사용자 관리 상태 로그를 추가로 MongoDB에 저장
  src/main/java/org/highfive/backend/action/ActionLogService.java
Labels: feat

#297 feat[#296]: PresignedUrl 생성시 S3 imageUrl 같이 반환하기
  src/main/java/org/highfive/backend/infra/s3/controller/S3Controller.java
  src/main/java/org/highfive/backend/infra/s3/dto/PresignedUploadResponse.java
  src/main/java/org/highfive/backend/infra/s3/service/S3Service.java
Labels: feat

#300 Refactor[#298]: 시간으로 쇼츠 댓글 조회하는 기능 복구
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsCommentMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsCommentsByIdResponseDto.java
  src/main/java/org/highfive/backend/shorts/dto/response/ShortsCommentsByTimeResponseDto.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: refactor

#301 Feat[#299] RabbitMQ 메시지 전송 3번 재처리 후, 실패한 경우 행동로그 상태 fail로 갱신하기 + 로그 남기기
  src/main/java/org/highfive/backend/action/ActionLogAspect.java
  src/main/java/org/highfive/backend/action/ActionLogService.java
  src/main/java/org/highfive/backend/action/exception/ActionLogErrorCode.java
  src/main/java/org/highfive/backend/action/log/strategy/ClickActionLogStrategy.java
  src/main/java/org/highfive/backend/action/log/strategy/LikeActionLogStrategy.java
  src/main/java/org/highfive/backend/action/log/strategy/RatingActionLogStrategy.java
  src/main/java/org/highfive/backend/action/log/strategy/WatchActionLogStrategy.java
  src/main/java/org/highfive/backend/rabbitmq/dto/UserWeightUpdateMessageDto.java
  src/main/java/org/highfive/backend/rabbitmq/dto/mapper/MessageMapper.java
  src/main/java/org/highfive/backend/rabbitmq/producer/RecommendationMessageProducer.java
Labels: feat

#307 fix[#306]: 쇼츠 댓글 조회를 id 기준으로 오름차순으로 수정
  src/main/java/org/highfive/backend/shorts/repository/querydsl/ShortsCommentQueryRepository.java
Labels: fix

#310 fix[#309]: 나의 리뷰 조회시 사용되는 cursor의 자료형을 long형으로 전환
  src/main/java/org/highfive/backend/review/repository/jpa/ReviewRepository.java
  src/main/java/org/highfive/backend/user/controller/UserController.java
  src/main/java/org/highfive/backend/user/service/UserService.java
Labels: fix

#321 Feat[#320]: 쇼츠 댓글 작성 요청 시 작성한 댓글 정보를 응답으로 제공
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
  src/main/java/org/highfive/backend/shorts/dto/mapper/ShortsCommentMapper.java
  src/main/java/org/highfive/backend/shorts/dto/response/CreateShortsCommentResponseDto.java
  src/main/java/org/highfive/backend/shorts/service/ShortsService.java
Labels: feat, refactor

#324 Refactor[#319] : 시청 시간 로그 생성 시 검증 로직 제거
  src/main/java/org/highfive/backend/user/controller/UserLogController.java
  src/main/java/org/highfive/backend/user/service/UserLogService.java
Labels: refactor

#327 Refactor[#326]: 홈 화면에서 큐레이션 조회 시 에디터의 프로필 url 반환
  src/main/java/org/highfive/backend/content/dto/response/HomeContentsResponseDto.java
  src/main/java/org/highfive/backend/curation/dto/mapper/CurationMapper.java
Labels: refactor

#329 Feat[#328] 큐레이션 생성 및 조회시 설명 추가하기
  src/main/java/org/highfive/backend/curation/dto/mapper/CurationMapper.java
  src/main/java/org/highfive/backend/curation/dto/response/CurationDetailResponseDto.java
  src/main/java/org/highfive/backend/curation/dto/response/MyCurationResponseDto.java
Labels: feat

#336 Refactor[#333]: 홈 화면 큐레이션 응답 시 컨텐츠 id, 컨텐츠 썸네일 url 포함하여 응답
  src/main/java/org/highfive/backend/content/dto/response/HomeContentsResponseDto.java
  src/main/java/org/highfive/backend/curation/dto/mapper/CurationMapper.java
Labels: refactor

#335 Feat[#332] 컨텐츠 추가시 DB에 저장되는 url을 변경해서 저장하기 #332
  src/main/java/org/highfive/backend/content/dto/mapper/ContentMapper.java
  src/main/java/org/highfive/backend/content/entity/Content.java
  src/main/java/org/highfive/backend/metadata/entity/MetaInfo.java
Labels: feat

#340 Feat[#337] : 시청 시간 로그 생성 시 유저 평균 시청시간, 시청 개수 업데이트 로직 추가
  src/main/java/org/highfive/backend/user/controller/UserLogController.java
  src/main/java/org/highfive/backend/user/entity/User.java
  src/main/java/org/highfive/backend/user/service/UserLogService.java
Labels: feat

#343 Feat[#341] : 리뷰 생성, 수정, 삭제 시 유저 평균 평점 업데이트 로직 추가
  src/main/java/org/highfive/backend/review/repository/jpa/ReviewRepository.java
  src/main/java/org/highfive/backend/review/service/ReviewService.java
  src/main/java/org/highfive/backend/user/entity/User.java
Labels: feat

#345 Refactor[#342] : 에러 로그 알림 스크립트 제거
  src/main/java/org/highfive/backend/infra/docker/Dockerfile
  src/main/java/org/highfive/backend/infra/docker/alert-watcher.sh
Labels: refactor

#352 Feat[#351]: S3 쇼츠 전용, 비디오 전용 preSignedUrl 생성
  src/main/java/org/highfive/backend/infra/s3/MediaType.java
  src/main/java/org/highfive/backend/infra/s3/controller/S3Controller.java
  src/main/java/org/highfive/backend/infra/s3/dto/ContentsPresignedUrlResponseDto.java
  src/main/java/org/highfive/backend/infra/s3/dto/CurationPresignedUrlResponseDto.java
  src/main/java/org/highfive/backend/infra/s3/dto/UrlPair.java
  src/main/java/org/highfive/backend/infra/s3/service/S3Service.java
Labels: feat

#353 Refactor[#350]: 온보딩 제출 후 사용자 가중치를 MongoDB에 저장
  src/main/java/org/highfive/backend/content/service/OnboardingService.java
  src/main/java/org/highfive/backend/global/util/WeightManager.java
  src/main/java/org/highfive/backend/user/entity/preference/MongoUserWeight.java
  src/main/java/org/highfive/backend/user/repository/mongo/UserWeightRepository.java
  src/test/java/org/highfive/backend/content/service/OnboardingServiceTest.java
Labels: refactor

#358 feat[#356]: 메타정보 타입에 대한 데이터를 메시지로 추가로 보내기
  src/main/java/org/highfive/backend/action/ActionLogService.java
  src/main/java/org/highfive/backend/rabbitmq/dto/UserWeightUpdateMessageDto.java
  src/main/java/org/highfive/backend/rabbitmq/dto/mapper/MessageMapper.java
Labels: feat

#359 Refactor[#357]: Action Log 저장 시 metaInfo의 형식을 List가 아닌 Map 형식으로 저장
  src/main/java/org/highfive/backend/action/log/ActionLogMapper.java
  src/main/java/org/highfive/backend/action/log/MetaInfoLog.java
Labels: refactor

#365 feat[#364]: 유사도가 높은 20개의 작품중 랜덤한 상품을 전달하도록 구현
  src/main/java/org/highfive/backend/content/repository/jpa/ContentRepository.java
Labels: feat

#370 Feat[#369] : 쇼츠 좋아요 취소 시 DISLIKE 행동 로그 추가
  src/main/java/org/highfive/backend/action/Action.java
  src/main/java/org/highfive/backend/action/log/ActionLogStrategyFactory.java
  src/main/java/org/highfive/backend/action/log/strategy/DislikeActionLogStrategy.java
  src/main/java/org/highfive/backend/shorts/controller/ShortsController.java
Labels: feat
